// Common Italian first names (masculine and feminine)
export const NOMI_ITALIANI = new Set([
  // Maschili - top 100+
  'marco', 'giuseppe', 'giovanni', 'antonio', 'mario', 'luigi', 'francesco',
  'angelo', 'vincenzo', 'pietro', 'salvatore', 'carlo', 'franco', 'domenico',
  'bruno', 'paolo', 'michele', 'giorgio', 'aldo', 'sergio', 'luciano',
  'roberto', 'andrea', 'stefano', 'alessandro', 'massimo', 'claudio',
  'enrico', 'alberto', 'luca', 'davide', 'matteo', 'simone', 'fabio',
  'riccardo', 'daniele', 'emanuele', 'filippo', 'nicola', 'tommaso',
  'lorenzo', 'leonardo', 'gabriele', 'edoardo', 'giacomo', 'federico',
  'diego', 'samuele', 'cristian', 'manuel', 'christian', 'mirko',
  'ivan', 'mauro', 'gianluca', 'gianfranco', 'giancarlo', 'gianluigi',
  'pierluigi', 'piergiorgio', 'pier', 'giampaolo', 'gianmaria',
  'raffaele', 'pasquale', 'carmelo', 'gaetano', 'rocco', 'cosimo',
  'alfredo', 'cesare', 'dario', 'danilo', 'donato', 'elia', 'emilio',
  'ernesto', 'eugenio', 'ezio', 'fabrizio', 'fernando', 'flavio',
  'fulvio', 'gianni', 'gilberto', 'giulio', 'guido', 'igino', 'italo',
  'ivano', 'jacopo', 'lauro', 'livio', 'lucio', 'marcello', 'marino',
  'massimiliano', 'maurizio', 'nando', 'nino', 'olindo', 'oreste',
  'oscar', 'osvaldo', 'ottavio', 'patrizio', 'remo', 'renzo', 'rinaldo',
  'romeo', 'ruggero', 'sandro', 'saverio', 'silvano', 'silvio', 'tiziano',
  'ugo', 'umberto', 'valerio', 'vittorio', 'walter',
  // Femminili - top 100+
  'maria', 'anna', 'giuseppina', 'rosa', 'angela', 'giovanna', 'teresa',
  'lucia', 'carmela', 'francesca', 'anna maria', 'antonietta', 'carla',
  'elena', 'concetta', 'rita', 'margherita', 'franca', 'paola', 'laura',
  'grazia', 'liliana', 'silvana', 'giuliana', 'luisa', 'bruna', 'rina',
  'ida', 'graziella', 'marina', 'adriana', 'gabriella', 'patrizia',
  'daniela', 'barbara', 'claudia', 'monica', 'cristina', 'valentina',
  'sara', 'chiara', 'giulia', 'martina', 'alessia', 'elisa', 'silvia',
  'simona', 'roberta', 'federica', 'alessandra', 'veronica', 'ilaria',
  'michela', 'serena', 'sabrina', 'manuela', 'cinzia', 'tiziana',
  'elisabetta', 'marta', 'irene', 'beatrice', 'alice', 'giada', 'aurora',
  'giorgia', 'eleonora', 'sofia', 'noemi', 'greta', 'arianna', 'viola',
  'bianca', 'emma', 'matilde', 'rebecca', 'vanessa', 'jessica', 'debora',
  'rachele', 'stella', 'nadia', 'ornella', 'lorena', 'ivana', 'mirella',
  'rosa maria', 'anna rosa', 'maria grazia', 'maria teresa', 'maria luisa',
  'maria rosa', 'maria pia', 'anna maria', 'maria cristina', 'maria antonietta'
])

// Common Italian surnames - top 200+
export const COGNOMI_ITALIANI = new Set([
  'rossi', 'russo', 'ferrari', 'esposito', 'bianchi', 'romano', 'colombo',
  'ricci', 'marino', 'greco', 'bruno', 'gallo', 'conti', 'de luca',
  'costa', 'giordano', 'mancini', 'rizzo', 'lombardi', 'moretti',
  'barbieri', 'fontana', 'santoro', 'mariani', 'rinaldi', 'caruso',
  'ferrara', 'galli', 'martini', 'leone', 'longo', 'gentile', 'martinelli',
  'vitale', 'lombardo', 'serra', 'coppola', 'de santis', 'damico',
  'marchetti', 'pellegrini', 'palumbo', 'piras', 'fabbri', 'sala',
  'marini', 'grasso', 'valentini', 'messina', 'sala', 'de angelis',
  'bianco', 'monti', 'cattaneo', 'guerra', 'silvestri', 'bernardi',
  'martino', 'conte', 'villa', 'landi', 'ferri', 'benedetti', 'farina',
  'morelli', 'amato', 'cattaneo', 'grassi', 'negri', 'sanna', 'pagano',
  'testa', 'neri', 'palermo', 'donati', 'rizzi', 'poli', 'orlando',
  'damiani', 'rossetti', 'ruggiero', 'sorrentino', 'ferraro', 'caputo',
  'pellegrino', 'giuliani', 'parisi', 'luciani', 'barone', 'dambrosio',
  'alberti', 'basile', 'riva', 'rossini', 'castelli', 'fiore', 'sartori',
  'franco', 'battaglia', 'donato', 'martins', 'vitiello', 'gambino',
  'pugliese', 'calabrese', 'siciliano', 'napoletano', 'palumbo',
  'montanari', 'marchese', 'deluca', 'desantis', 'deangelis',
  'dipietro', 'dimaio', 'dimaggio', 'dibenedetto', 'dagostino',
  'dalesio', 'delia', 'delgrosso', 'delprete', 'delvecchio',
  'bellini', 'bernini', 'borrelli', 'bruni', 'bucci', 'capasso',
  'cappelli', 'carbone', 'cardone', 'carnevale', 'casella', 'cavaliere',
  'ceccarelli', 'chiara', 'ciccone', 'clemente', 'cosentino', 'criscuolo',
  'dandrea', 'danna', 'dantonio', 'demarco', 'ferrante', 'ferro',
  'fiorentino', 'forte', 'gagliardi', 'gargiulo', 'germano', 'giannini',
  'grande', 'guarnieri', 'iannone', 'innocenti', 'lanza', 'leonardi',
  'luciano', 'maggio', 'mancuso', 'mantovani', 'marconi', 'massa',
  'mazza', 'meloni', 'mercuri', 'miccoli', 'migliore', 'milani',
  'molinari', 'montalto', 'napoli', 'natale', 'oliveri', 'pace',
  'padovano', 'palma', 'papa', 'pastore', 'perrone', 'petrucci',
  'piazza', 'piccolo', 'pisano', 'pozzi', 'proietti', 'puglisi',
  'quadri', 'raimondi', 'rapuano', 'renzi', 'ricciardi', 'rocca',
  'rosati', 'ruggeri', 'sabatini', 'sacchi', 'salerno', 'santi',
  'sartor', 'scarpelli', 'silvestro', 'tarantino', 'tedesco', 'torre',
  'tozzi', 'trovato', 'vaccaro', 'ventura', 'verdi', 'volpe', 'zanetti'
])

// Prefixes that strongly indicate a person name follows
export const PREFISSI_NOME = [
  'sig\\.?', 'sig\\.ra', 'signor[ea]?',
  'dott\\.?', 'dott\\.ssa', 'dr\\.?',
  'avv\\.?', 'avvocato', 'avvocatessa',
  'ing\\.?', 'prof\\.?', 'rag\\.?', 'geom\\.?', 'arch\\.?'
]

// Words that are NEVER person names — common in legal Italian text
export const PAROLE_LEGALI = new Set([
  // Legal procedural terms
  'onere', 'deduce', 'deduzione', 'deduzioni', 'ricorrente', 'ricorso',
  'controricorso', 'appello', 'appellante', 'resistente', 'convenuto',
  'attore', 'attrice', 'tribunale', 'corte', 'cassazione', 'giudice',
  'presidente', 'procuratore', 'cancelliere', 'cancelleria',
  'sentenza', 'ordinanza', 'decreto', 'udienza', 'camera', 'consiglio',
  'sezione', 'sezioni', 'unite', 'collegio', 'relatore',
  // Common verbs/nouns that get capitalized at sentence start
  'presenta', 'deposita', 'propone', 'chiede', 'domanda', 'eccepisce',
  'lamenta', 'contesta', 'osserva', 'rileva', 'ritiene', 'risulta',
  'dispone', 'condanna', 'rigetta', 'accoglie', 'dichiara', 'annulla',
  'revoca', 'conferma', 'modifica', 'riforma', 'respinge', 'ammette',
  'illustra', 'specifica', 'indica', 'ravvisa', 'ribadisce', 'sembra',
  'scalfisce', 'vulnera', 'palesandosi', 'potendosi', 'renda',
  'accettata', 'condivisa', 'introdotte', 'riscontrabili', 'sarebbero',
  // Common nouns
  'motivo', 'ragioni', 'ragione', 'argomenti', 'argomentazioni',
  'proposta', 'definizione', 'istanza', 'decisione', 'memoria',
  'memorie', 'verbale', 'ispettivo', 'certificato', 'attestato',
  'supporto', 'documento', 'documenti', 'atti', 'fascicolo',
  'giudizio', 'processo', 'procedimento', 'procedura',
  'primo', 'secondo', 'terzo', 'quarto', 'quinto', 'sesto',
  'fatto', 'diritto', 'merito', 'rito', 'forma', 'sostanza',
  'parte', 'parti', 'lato', 'capo', 'punto', 'caso', 'modo',
  'legge', 'norma', 'norme', 'articolo', 'comma', 'lettera',
  'codice', 'regolamento', 'disposizione', 'disposizioni',
  'termine', 'termini', 'periodo', 'anno', 'data', 'giorno',
  'spese', 'somma', 'importo', 'pagamento', 'condanna',
  'funzione', 'natura', 'carattere', 'efficacia', 'validità',
  'necessaria', 'specificità', 'corrispondenza', 'concordanza',
  'violazione', 'nullità', 'inammissibilità', 'infondatezza',
  'realtà', 'fattuale', 'discrezionalità', 'facoltà',
  'elementi', 'presuntivi', 'probatoria', 'probatorio',
  'generale', 'speciale', 'originale', 'diverso', 'varie',
  'esclusivo', 'impiego', 'rilievo', 'riproduzione',
  'prossimità', 'certezza', 'tempestivo', 'irragionevole',
  'sanzionatoria', 'prettamente', 'solidalmente', 'responsabile',
  // Prepositions/articles that get capitalized
  'dal', 'dalla', 'dello', 'della', 'degli', 'delle',
  'nel', 'nella', 'nello', 'nelle', 'nei', 'negli',
  'sul', 'sulla', 'sullo', 'sulle', 'sui', 'sugli',
  'con', 'per', 'tra', 'fra', 'anche', 'solo',
  'non', 'più', 'ogni', 'alcuni', 'taluni', 'molti',
  'entrambi', 'dunque', 'riguardo', 'quanto', 'circa',
  'ufficiale', 'civile', 'penale', 'amministrativo',
  'lavoratori', 'lavoratore', 'datore', 'lavoro',
  'repubblica', 'italiana', 'stato', 'ministero',
  'comune', 'provincia', 'regione', 'italia',
  'indagini', 'corso', 'rep', 'ord', 'cron', 'reg',
  // Terms that appear in ALL CAPS in legal documents — NOT names
  'ordinanza', 'sentenza', 'decreto', 'istituto', 'nazionale',
  'previdenza', 'sociale', 'corte', 'appello', 'cassazione',
  'tribunale', 'sezione', 'anno', 'numero', 'legale',
  'rappresentante', 'tempore', 'rappresentato', 'rappresentata',
  'difeso', 'difesa', 'avvocati', 'avvocato', 'contro',
  'ricorrente', 'controricorrente', 'persona', 'oggetto',
  'obbligo', 'contributivo', 'datoriale', 'civile',
  'pubblicazione', 'deposito', 'depositata', 'proposto',
  'ricorso', 'materia', 'sezioni', 'unite', 'camera',
  'decisione', 'udienza', 'relazione', 'presidente',
  'relatore', 'consigliere', 'procuratore', 'sostituto',
  'pubblico', 'ministero', 'fatto', 'diritto', 'ragioni',
  'della', 'delle', 'degli', 'dello', 'dalla', 'nella',
  'inps', 'spa', 'srl', 'sas', 'snc',
  // Truncated prepositions/articles that appear as standalone words in PDFs
  'dell', 'dall', 'nell', 'sull', 'all', 'coll',
  // Titles/abbreviations that are NOT names
  'dott', 'dottore', 'dottoressa', 'prof', 'professore',
  'avv', 'sig', 'rag', 'geom', 'arch', 'ing',
  // Other common false positives
  'art', 'artt', 'sent', 'tab', 'lett', 'cpv',
  'ric', 'res', 'app', 'trib', 'cass', 'pres',
  'num', 'vol', 'cap', 'sez', 'par', 'cfr',
  'dir', 'proc', 'uff', 'det', 'del', 'doc',
  'est', 'int', 'ult', 'sup', 'inf', 'min', 'max',
  'cod', 'reg', 'leg', 'cost', 'pen', 'civ',
  'ecc', 'ivi', 'ora', 'poi', 'già', 'pur', 'ben',
  'così', 'però', 'cioè', 'ovvero', 'altresì', 'pertanto',
  'tuttavia', 'invero', 'laddove', 'qualora', 'sicché',
  // Common verbs/past participles that get capitalized and cause false positives
  'ha', 'lasciato', 'infatti', 'era', 'brigato', 'trovato',
  'detto', 'fatto', 'avuto', 'dato', 'preso', 'messo', 'tenuto',
  'visto', 'chiesto', 'risposto', 'deciso', 'ritenuto', 'stabilito',
  'disposto', 'ordinato', 'emesso', 'pronunciato', 'confermato',
  'accertato', 'contestato', 'eccepito', 'dedotto', 'prodotto',
  'acquisito', 'depositato', 'notificato', 'comunicato',
  'comparso', 'costituito', 'intervenuto', 'aderito'
])

